(source "gnu" "http://elpa.gnu.org/packages/")
(source "org" "http://orgmode.org/elpa/")
(source "melpa" "http://melpa.milkbox.net/packages/")
(source "marmalade" "http://marmalade-repo.org/packages/")

(depends-on "[cl-struct-package-desc company (0 6 12) Modular in-buffer completion framework nil tar gnu nil ((:url . http://company-mode.github.io/)) nil]")
(depends-on "[cl-struct-package-desc enh-ruby-mode (20131105 1956) Major mode for editing Ruby files [github] nil tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc git-gutter-fringe (0 12) Fringe version of git-gutter.el ((git-gutter (0 42)) (fringe-helper (0 1 1))) single marmalade nil nil nil]")
(depends-on "[cl-struct-package-desc inf-ruby (2 3 2) Run a Ruby process in a buffer nil single marmalade nil nil nil]")
(depends-on "[cl-struct-package-desc magit (20131114 1315) control Git from Emacs [github] ((cl-lib (0 3)) (git-commit-mode (0 14 0)) (git-rebase-mode (0 14 0))) tar melpa nil nil nil]")
(depends-on "[cl-struct-package-desc org (20131115) Outline-based notes management and organizer nil tar org nil nil nil]")
(depends-on "[cl-struct-package-desc robe (0 7 6) Code navigation, documentation lookup and completion for Ruby ((inf-ruby (2 3 0))) tar marmalade nil nil nil]")
(depends-on "pallet")
